# Generated by Django 3.1 on 2020-08-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='Highlights',
        ),
        migrations.DeleteModel(
            name='Highlights',
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
