# Generated by Django 3.1 on 2020-08-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MustufaJan', '0002_auto_20200826_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=500)),
                ('institution', models.CharField(max_length=500)),
                ('institution_description', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Work', 'Work')], default='Work', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=500)),
                ('headline', models.CharField(max_length=500)),
                ('Highlights', models.ManyToManyField(blank=True, related_name='relevant_role', to='MustufaJan.Highlight')),
            ],
        ),
    ]
