# Generated by Django 3.1 on 2020-08-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0003_highlight_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='end_date',
            field=models.DateField(),
        ),
    ]
