# Generated by Django 3.1 on 2020-08-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0004_auto_20200826_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
