# Generated by Django 3.1 on 2020-08-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0005_auto_20200826_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='icon_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='highlight',
            name='logo_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
