# Generated by Django 3.1 on 2020-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0006_auto_20200826_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
