# Generated by Django 3.1 on 2020-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0007_auto_20200827_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='profile',
            field=models.CharField(choices=[('Product Manager', 'Product Manager'), ('Software Developer', 'Sofware Developer')], default='Software Developer', max_length=20),
        ),
    ]
