# Generated by Django 3.1 on 2020-08-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0008_highlight_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='profile',
        ),
        migrations.AddField(
            model_name='highlight',
            name='profile',
            field=models.ManyToManyField(related_name='highlight', to='MustufaJan.Profile'),
        ),
    ]
