# Generated by Django 3.1 on 2020-08-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0009_auto_20200827_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Highlights',
        ),
        migrations.AddField(
            model_name='profile',
            name='highlights',
            field=models.ManyToManyField(blank=True, related_name='relevant_role', to='MustufaJan.Highlight'),
        ),
    ]
