# Generated by Django 3.1 on 2020-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0010_auto_20200827_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='profile',
            field=models.ManyToManyField(related_name='relevant_highlights', to='MustufaJan.Profile'),
        ),
    ]
