# Generated by Django 3.1 on 2020-08-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0011_auto_20200827_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('git_link', models.CharField(blank=True, max_length=500)),
                ('preview', models.CharField(blank=True, max_length=500)),
                ('logo_path', models.CharField(blank=True, max_length=500)),
                ('icon_path', models.CharField(blank=True, max_length=500)),
                ('tech_stack', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
