# Generated by Django 3.1 on 2020-09-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0014_auto_20200901_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.DecimalField(decimal_places=1, default=3.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='skill',
            name='years',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
