# Generated by Django 3.1 on 2020-09-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0015_auto_20200901_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='icon_path',
        ),
    ]
