# Generated by Django 3.1 on 2020-09-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0016_remove_highlight_icon_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='MustufaJan.project')),
            ],
        ),
    ]
