# Generated by Django 3.1 on 2020-09-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0017_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='MustufaJan.project'),
        ),
    ]
