# Generated by Django 3.1 on 2020-09-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0018_auto_20200910_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
