# Generated by Django 3.1 on 2020-09-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MustufaJan', '0019_auto_20200910_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.CharField(blank=True, default='SW', max_length=500),
        ),
    ]
